### ISSUE TITLE
Specify how to properly save the input file

### ISSUE THREAD

**Issue by FrancescoMassaini** [VeraPancaldiLab/GEMDeCan_deconvolution#6]
write.table(counts.TPM.normalized, "GEMDeCan_deconvolution/inputs/file_name.txt", quote = F, sep = "\t", row.names = F)
this code line of the README suggests that you start from this kind of format

| Genes | Sample1 | Sample2 | Sample3 |
|------|---------|---------|---------|
| g1   | 1.8     | 5.2     | 4.1     |
| g2   | 5.7     | 8.3     | 2.0     |
| g3   | 6.2     | 3.1     | 9.2     |
| g4   | 7.2     | 9.1     | 0.6     |

if the data is not already in this format you can use
rownames_to_column(.data, "Genes")

**Comment by mhurtado13** [comment]
Solved
