### ISSUE TITLE
README suggest

### ISSUE THREAD

**Issue by FrancescoMassaini** [VeraPancaldiLab/GEMDeCan_deconvolution#7]
In the README section:
Configure your workspace
    Input file should be save in folder inputs/
    Go to the file snakemake.yml and add the name of your input file in the section Mixtures

Add the same information you find in snakemake.yml:
- Uncomment the file you want to run.
- Add the input file in the input folder as well, with exactly the same name.
- In the snakemake mixtures list, do not add .txt at the end of the file name.

**Comment by mhurtado13** [comment]
Solved
